### ISSUE TITLE
What purpose does this piece of code solve in main.css

### ISSUE THREAD

**Issue by invalidtoken** [Real-Dev-Squad/website#39]
https://github.com/Real-Dev-Squad/website/blob/27916a54feca6d048cc370d7005975cd084ba31c/css/main.css#L8-L17

Hi group, just want to know what purpose does this piece of code solves. I tried to look at the live website to understand but didn't get much.

**Comment by takshch** [comment]
I included that code for good looking background but someone removed only background property instead of removing full code of background from main.css.  
If realdevsquad don't want designed background then they can remove this pseudo element from the code.
`Img File: tswhirls.png`

**Comment by takshch** [comment]
`pseudo element` is not removed. Only background property is removed. 
Issue-#34

**Comment by takshch** [comment]
@invalidtoken @ankushdharkar 
https://github.com/Real-Dev-Squad/website/pull/40
Please review this PR and merge.
This PR is solution for this issue-#39

**Comment by invalidtoken** [comment]
@takshch so what's the difference between just setting the background of body and using pseudo-classes for setting the background. What are the advantages of using this pseudo-class approach?
