### ISSUE TITLE
Show "Hello, <name>" instead of Login

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website#52]
If the current user is already logged in, we want to show "Hello, <name>", instead of the the login button

<img width="600" alt="login" src="https://user-images.githubusercontent.com/1935403/91636522-f21b1100-ea1e-11ea-8666-ab4fc5296e80.png">

We can use the user details API to figure out the user's name. Please ask the backend team to update the [API contracts](https://github.com/Real-Dev-Squad/website-api-contracts)

**Comment by swarajpure** [comment]
Issue solved. Refer #57 #62 and #63 for solution.
Closing this issue.
